Copy

obj-m += va_space.o
 
# Adjust KDIR if your kernel headers are elsewhere
KDIR ?= /lib/modules/$(shell uname -r)/build
 
all:
	make -C $(KDIR) M=$(PWD) modules
 
clean:
	make -C $(KDIR) M=$(PWD) clean
 